CREATE TABLE BENIPAYO_CUST (
CUST_ID INT,
LAST_NAME VARCHAR(MAX),
FIRST_NAME VARCHAR (MAX),
ADDRESS VARCHAR (MAX),
CITY VARCHAR (50),
STATE VARCHAR (2),
ZIP_CODE VARCHAR (10),
ACCT_NUM VARCHAR (10));

SELECT * FROM BENIPAYO_CUST;

INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (110, 'CASH', 'ASSET')

CREATE TABLE BENIPAYO_VEND (
VEND_ID INT,
VEND_NAME VARCHAR(MAX),
ADDRESS VARCHAR (MAX),
CITY VARCHAR (50),
STATE VARCHAR (2),
ZIP_CODE VARCHAR (10),
ACCT_NUM VARCHAR (10));

SELECT * FROM BENIPAYO_VEND;

CREATE TABLE BENIPAYO_COA (
COA_ID INT,
ACCT_NAME VARCHAR(MAX),
ACCT_TYPE VARCHAR (MAX),
DEBIT_AMT VARCHAR (MAX),
CREDIT_AMT VARCHAR (MAX));

SELECT * FROM BENIPAYO_COA;

INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (110, 'CASH', 'ASSET')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (120, 'ACCOUNTS RECEIVABLE', 'ASSET')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (121, 'ACCOUNTS RECEIVABLE SUB', 'ASSET-SUB')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (122, 'ACCOUNTS RECEIVABLE SUB', 'ASSET-SUB')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (123, 'ACCOUNTS RECEIVABLE SUB', 'ASSET-SUB')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (124, 'ACCOUNTS RECEIVABLE SUB', 'ASSET-SUB')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (125, 'ACCOUNTS RECEIVABLE SUB', 'ASSET-SUB')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (126, 'ALLOWANCE OF DOUBTFUL ACCTS', 'CONTRA ASSET')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (130, 'INVENTORY', 'ASSET')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (131, 'INVENTORY SUB', 'ASSET-SUB')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (132, 'INVENTORY SUB', 'ASSET-SUB')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (133, 'INVENTORY SUB', 'ASSET-SUB')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (134, 'INVENTORY SUB', 'ASSET-SUB')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (135, 'INVENTORY SUB', 'ASSET-SUB')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (160, 'EQUIPMENT', 'ASSET')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (161, 'ACCUM DEP-EQUIPMENT', 'ASSET')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (170, 'BUILDING', 'ASSET')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (175, 'ACCT DEPREC-BUILDING', 'CONTRA ASSET')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (210, 'ACCOUNTS PAYABLE', 'LIABILITY')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (211, 'ACCOUNTS PAYABLE', 'LIAB-SUB')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (212, 'ACCOUNTS PAYABLE', 'LIAB-SUB')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (213, 'ACCOUNTS PAYABLE', 'LIAB-SUB')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (214, 'ACCOUNTS PAYABLE', 'LIAB-SUB')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (215, 'ACCOUNTS PAYABLE', 'LIAB-SUB')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (310, 'COMMON STOCK', 'EQUITY')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (320, 'TREASURY STOCK', 'EQUITY')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (330, 'RETAINED EARNINGS', 'EQUITY')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (410, 'SALES REVENUE', 'REVENUE')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (420, 'SALES RETURN', 'REVENUE')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (510, 'COST OF GOODS SOLD', 'EXPENSE')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (520, 'ADVERTISING EXPENSE', 'EXPENSE')
INSERT INTO BENIPAYO_COA(COA_ID, ACCT_NAME, ACCT_TYPE) VALUES (530, 'DEP EXPENSE-BUILDING', 'EXPENSE')





